version: 1
disable_existing_loggers: False

formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: server.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  error_file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    level: ERROR

root:
  level: INFO
  handlers: [console, file]

loggers:
  vcs:
    level: INFO
    handlers: [console, file, error_file]
    propagate: False
  api:
    level: INFO
    handlers: [console, file, error_file]
    propagate: False
  cache:
    level: INFO
    handlers: [console, file]
    propagate: False
